### ISSUE TITLE
Duplication of user games

### ISSUE THREAD

**Issue by GLeviRodriguez** [bmcgary/TicketToRide#12]
@thyer The user class currently contains a list of gameIDs to store the user's joined games, but the getUserGames function in the server facade ignores this and searches through all games. Can we remove this duplication?

**Comment by thyer** [comment]
It's a bit of a crapshoot on this one. We could easily return all the gameIDs, except the method is supposed to return all Games, not just the IDs. That means no matter what, we have to go throught he list of Games and check each one to see if it maches an ID the User has.

**Comment by GLeviRodriguez** [comment]
I think what we return is fine. I'm not so sure we need to keep that list of gameIds in the user class if we're not using it.

**Comment by thyer** [comment]
Should be fixed by 0bd0cbaee8a4998cc85068fc14ec38bce634b87d
