### ISSUE TITLE
Player can register with invalid username and password

### ISSUE THREAD

**Issue by ojaneeo** [bmcgary/TicketToRide#19]
Players can register with usernames and passwords that are too long

Usernames and passwords must be less than 25 characters. And passwords must be at least 4

**Comment by thyer** [comment]
Did I miss this in the spec? I just looked again and couldn't find these restrictions.

**Comment by ojaneeo** [comment]
I don't think it was in the spec, it was something we decided when writing the test cases. We were mostly thinking the client side shouldn't allow input that big

**Comment by thyer** [comment]
Alright. Just as an FYI, server side demands username/password length be at least 4, not 5. We also don't have a limit on length, but do throw an exception if we detect any non-alphanumeric characters.

**Comment by ojaneeo** [comment]
Great! we can change that password minimum to 4 then too

**Comment by thyer** [comment]
Let me know if there's anything else we can do Server-side to help.

2016-03-19 12:40 GMT-06:00 ojaneeo <notifications@github.com>:

> Great! we can change that password minimum to 4 then too
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bmcgary/TicketToRide/issues/19#issuecomment-198764289>
>



-- 
Trent Hyer
C: (801) 971-5593
E: hyer.trent@gmail.com
S: trenthyer.com
