### ISSUE TITLE
3 wilds on the front facing cards

### ISSUE THREAD

**Issue by bmcgary** [bmcgary/TicketToRide#26]
If there is ever 3 or more wild cards in the 5 front facing cards all 5 cards are discarded and 5 new cards are put up. Currently the server doesn't do that.

**Comment by thyer** [comment]
It turns out this fix is really complex in some edge cases. For example, what if there are only 8 train cards left and 6 of them are wild? I'm purposefully going to have to leave some holes in this so we can't run an infinite loop.

**Comment by ojaneeo** [comment]
That will probably be fine

**Comment by ojaneeo** [comment]
I don't think your fix is working for me...

**Comment by thyer** [comment]
@ojaneeo are you on master or TrentsBranch?

**Comment by ojaneeo** [comment]
Master

**Comment by ojaneeo** [comment]
that's the only one that git shows me. But I'm kind of a git noob.

**Comment by thyer** [comment]
Ah, yes. I haven't merged these changes into master yet. You can change branches in terminal by using git checkout <branch_name>
