### ISSUE TITLE
Server ends the game one turn too soon

### ISSUE THREAD

**Issue by Jacobtk** [bmcgary/TicketToRide#29]
From the rules: "When one player’s stock of colored plastic trains gets down to only 0,1 or 2 trains left at  the end of his turn, each player, including that player, gets one final turn."
We currently aren't giving the player who got down to 2 or fewer trains their last turn.

**Comment by bmcgary** [comment]
Thanks Trent for staying on top of this. Knew we could count on youDate: Wed, 10 Aug 2016 15:13:40 -0700
