### ISSUE TITLE
Need to indicate which cards are used in BuyRoute from ServerFacade on down the stack

### ISSUE THREAD

**Issue by thyer** [bmcgary/TicketToRide#8]
@Jacobtk here's the issue I said I was opening earlier in response to your items.

**Comment by thyer** [comment]
@Jacobtk or @198xiaozhu when either of you get a moment, would you mind doing a sanity check on this?

**Comment by Jacobtk** [comment]
@thyer 
- PlayerManager's canBuyTrack is being called twice. Once from Game's canPlayerBuyRoute and once from PlayerManager's canBuyTrackWithCards.
- It seems like PlayerManager's canBuyRouteWithCards would allow a user to buy a grey route using multiple non-wild colors at a time. For instance, would this function allow a user to buy a grey route of length 2 with one blue card and one orange card?
- PlayerManager's canBuyTrackWithCards is being called twice. Once in ServerFacade's canBuyRoute and once in Game's buyRoute.

**Comment by thyer** [comment]
- Fixed in commit I'll push soon
- No, there's a break statement after subtracting the first color from the wildsNeeded that makes it so only one color can be used (unless wilds are used, in which case one color and wild may be used)
- Fixed as well.

**Comment by thyer** [comment]
Closing this issue
